In [1]:
#텐서 생성 및 변환
#텐서는 파이토치의 가장 기본이 되는 데이터 구조
#넘파이의 ndarray와 비슷하며 GPU에서의 연산도 가능
import torch
print(torch.tensor([[1,2],[3,4]])) #2x2 형태의 텐서 생성
print(torch.tensor([[1,2],[3,4]], device="cuda:0")) #GPU에 텐서 생성
print(torch.tensor([[1,2],[3,4]], dtype=torch.float64)) #dtype 실수를 이용하여 텐서 생성

tensor([[1, 2],
        [3, 4]])
tensor([[1, 2],
        [3, 4]], device='cuda:0')
tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)


In [2]:
#텐서의 자료형
#torch.FloatTensor : 32비트의 부동 소수점
#torch.DoubleTensor : 64비트의 부동 소수점
#torch.LongTensor : 64비트의 부호가 있는 정수

In [3]:
#텐서 인덱스 조작 - 인덱스 지정, 슬라이스
#텐서 연산
temp=torch.FloatTensor([1,2,3,4,5,6,7,8])
print(temp[0], temp[1], temp[-1])
print('----------------------------')
print(temp[2:5], temp[4:-1])
#
v=torch.tensor([1,2,3])
w=torch.tensor([3,4,6])
print(w-v)

tensor(1.) tensor(2.) tensor(8.)
----------------------------
tensor([3., 4., 5.]) tensor([5., 6., 7.])
tensor([2, 2, 3])


In [4]:
#텐서 다루기
#view - 차원 변경, 넘파이의 ndarray
#cat - 다른 길이 텐서를 하나로 병합, 결합
#transpose(t) - 차원 교환, 차원 순서 변경, 행렬 전치
#shape - 텐서 사이즈
temp=torch.tensor([[1,2],[3,4]]) #2x2 행렬 생성

print(temp.shape)
print(temp.view(4,1)) #2x2 행렬을 4x1 행렬로 변형
print(temp.view(-1)) #2x2 행렬을 1차원 벡터로 변형
print(temp.view(1,-1)) #-1은 (1,?), 다른 차원으로부터 해당 값을 유추 -> (1,4)
print(temp.view(-1,1)) #(?,1) -> (4,1)

torch.Size([2, 2])
tensor([[1],
        [2],
        [3],
        [4]])
tensor([1, 2, 3, 4])
tensor([[1, 2, 3, 4]])
tensor([[1],
        [2],
        [3],
        [4]])


In [5]:
# 텐서
import torch
import numpy as np

x=torch.empty(5,4) #5x4 행렬인 빈 empty 텐서 생성
print(x)

tensor([[-1.5477e+05,  3.1681e-41,  0.0000e+00,  0.0000e+00],
        [-1.1611e+05,  3.1681e-41, -1.6561e+03,  3.1681e-41],
        [-2.2638e+24,  4.3391e-41,  1.4013e-45,  0.0000e+00],
        [ 4.2039e-45,  0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00]])


In [6]:
torch.ones(3,3) #1로 3x3 행렬의 텐서 생성

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [8]:
torch.zeros(2) #0으로 1x2 행렬의 텐서 생성

tensor([0., 0.])

In [9]:
torch.zeros(2,2) #0으로 2x2 행렬의 텐서 생성

tensor([[0., 0.],
        [0., 0.]])

In [11]:
torch.empty(4,5)

tensor([[-1.4705e+05,  3.1681e-41, -4.3178e+04,  3.1681e-41,  8.9683e-44],
        [ 0.0000e+00,  1.1210e-43,  0.0000e+00,  1.6498e+08,  3.1688e-41],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00]])

In [13]:
torch.rand(5,6) #5x6 행렬의 random 숫자의 텐서 생성

tensor([[0.5181, 0.6455, 0.0147, 0.8238, 0.9642, 0.3339],
        [0.4517, 0.0341, 0.7932, 0.8800, 0.9620, 0.1532],
        [0.1077, 0.1394, 0.2179, 0.7420, 0.5792, 0.3108],
        [0.0776, 0.2704, 0.2082, 0.2913, 0.1528, 0.6088],
        [0.1030, 0.1136, 0.6278, 0.6805, 0.7355, 0.6072]])

In [14]:
#리스트, 넘파이 배열 텐서로 만들기

l = [13,4]
r =np.array([4,56,7])
torch.tensor(l)

tensor([13,  4])

In [15]:
torch.tensor(r)

tensor([ 4, 56,  7])

In [16]:
x.size()[1] #x 텐서 (5x4)
#x.size(1) 동일 값

4

In [21]:
x.size()[0] #= x.size(0)

5

In [22]:
torch.Size([5,4])

torch.Size([5, 4])

In [23]:
x=torch.rand(2,2)
y=torch.rand(2,2)
print(x)
print(y)
print(x+y)

tensor([[0.2060, 0.9217],
        [0.0627, 0.2991]])
tensor([[0.4724, 0.4324],
        [0.1451, 0.0362]])
tensor([[0.6784, 1.3542],
        [0.2078, 0.3353]])


In [26]:
torch.add(x,y) #add 덧셈 메소드
#인플레이스 연산 -원본 텐서의 값을 변경하며, 메모리를 절약할 수 있는 장점

tensor([[0.6784, 1.3542],
        [0.2078, 0.3353]])

In [27]:
y.add(x) #y에 x값을 더한다.

tensor([[0.6784, 1.3542],
        [0.2078, 0.3353]])

In [28]:
#텐서의 크기 변환
x=torch.rand(8,8)
print(x.size())

torch.Size([8, 8])


In [33]:
a=x.view(64) #8x8 -> 64
print(a.size())
print(a)

torch.Size([64])
tensor([0.4805, 0.1782, 0.7700, 0.1910, 0.0460, 0.7567, 0.3588, 0.9547, 0.3656,
        0.8780, 0.2002, 0.5380, 0.7538, 0.2266, 0.9623, 0.4814, 0.2145, 0.3811,
        0.5600, 0.9983, 0.9408, 0.2399, 0.4423, 0.9821, 0.0954, 0.3326, 0.4483,
        0.7515, 0.3107, 0.5356, 0.6746, 0.9447, 0.9596, 0.5250, 0.0647, 0.1064,
        0.3359, 0.5880, 0.8505, 0.3717, 0.2191, 0.8838, 0.5795, 0.5147, 0.0345,
        0.6762, 0.7164, 0.5372, 0.5655, 0.5580, 0.0552, 0.3084, 0.7700, 0.9884,
        0.0828, 0.1758, 0.7702, 0.1511, 0.3012, 0.0315, 0.2014, 0.5495, 0.5821,
        0.4772])


In [36]:
x=torch.rand(8,8)
y=x.numpy()
print(type(x))
print(type(y))

<class 'torch.Tensor'>
<class 'numpy.ndarray'>


In [38]:
x=torch.ones(1)
print(x)
print(x.item()) #item -텐서 값을 텐서가 아닌 값으로 만들어줌 = tensor에 저장된 값 가져오는 법

tensor([1.])
1.0


In [42]:
#텐서 조작하기
#뷰 view -원소의 수를 유지하면서 텐서의 크기 변경 (넘파이 reshape)

t=np.array([[[0,1,2],
            [3,4,5]],
           [[6,7,8],
            [9,10,11]]])
r=torch.FloatTensor(t)
print(r.shape)
print('------------------------------')
print(t)
print(r)

torch.Size([2, 2, 3])
------------------------------
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
tensor([[[ 0.,  1.,  2.],
         [ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.],
         [ 9., 10., 11.]]])


In [46]:
#3차원 -> 2차원으로 변경하기
#r 텐서를 2차원으로 변경해보자
#view()

#-1 다른 차원으로부터 해당 값을 유추한다.
print(r.view([-1,3])) #2차원으로 -1 view, 3열으로 보고싶어서 3 지정
print(r.view([-1,3]).shape)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


In [45]:
print(r.view([-1,2]))
print(r.view([-1,2]).shape)

tensor([[ 0.,  1.],
        [ 2.,  3.],
        [ 4.,  5.],
        [ 6.,  7.],
        [ 8.,  9.],
        [10., 11.]])
torch.Size([6, 2])


In [47]:
print(r.view([-1,4]))
print(r.view([-1,4]).shape)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])
torch.Size([3, 4])


In [48]:
print(r.view([-1,5])) #5열은 에러 발생
print(r.view([-1,5]).shape)

RuntimeError: shape '[-1, 5]' is invalid for input of size 12

In [49]:
print(r.view([-1,6]))
print(r.view([-1,6]).shape)

tensor([[ 0.,  1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10., 11.]])
torch.Size([2, 6])


In [51]:
#스퀴즈 Squeeze - n차원이 1인 경우 해당 차원을 제거를 한다.

re=torch.FloatTensor([[0],[1],[2]])
print(re)
print(re.shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [53]:
print(re.squeeze()) #squeeze로 1열 차원 제거
print(re.squeeze().shape) #(3,1) -> (3,) 변경

tensor([0., 1., 2.])
torch.Size([3])


In [54]:
#Unsqueeze - n차원이 1인 차원을 추가할 수 있다. (Squeeze 반대 개념)

ft=torch.Tensor([0,1,2])
print(ft.shape)

torch.Size([3])


In [56]:
print(ft.unsqueeze(0)) #0번째 차원 추가하기
print(ft.unsqueeze(0).shape) #3x1 -> 1x3의 2차원으로 변경되었음

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [ ]:
#타입 캐스팅 Type Casting

#32비트 torch.FlaotTensor
#64비트 torch.LongTensor
#Gpu torch.cuda.FloatTensor

In [58]:
x=torch.FloatTensor([1,2,3,4])
print(x)

tensor([1., 2., 3., 4.])


In [62]:
x=torch.LongTensor([1,2,3,4])
print(x)
print(x.float()) #float() 함수로 정수->실수 변경 가능

tensor([1, 2, 3, 4])
tensor([1., 2., 3., 4.])


In [63]:
x=torch.torch.cuda.FloatTensor([1,2,3,4])
print(x)

tensor([1., 2., 3., 4.], device='cuda:0')


In [64]:
bt=torch.ByteTensor([True,False,False,True])
print(bt)

tensor([1, 0, 0, 1], dtype=torch.uint8)


In [ ]:
https://wikidocs.net/52846