<Numpy 기초문법>
1. Numpy 라이브러리 개요
- Numpy: 파이썬을 위한 행렬(matrix) 라이브러리
- 과학적 계산을 위해 파이썬에서 제작
- 이산수학과 무작위 수 생성 등 수많은 작업을 할 수 있는 기능이 제공됨
- 벡터와 행렬을 위한 특수한 배열 형식을 제공
- 생성될 때 크기가 정해짐
- 텐서플로우와 잘 어울림
- 기계학습에서는 파이썬의 기본 리스트로 충분하지 않다.
- 데이터를 처리할 때는 리스트와 리스트 간의 연산이 가능해야 하는데 파이썬의 기본 리스트는 이것을 지원하지 않기 때문이다.
- 연산 속도도 중요하기 때문에 데이터 과학자들은 기본 리스트 대신에 넘파이(Numpy)를 선호한다.

In [1]:
#리스트 vs 넘파이 배열

#리스트 -> 리스트 간의 연산이 불가능함
mid_scores=[10,20,30]
final_scores=[70,80,90]

total = (mid_scores + final_scores)
total

[10, 20, 30, 70, 80, 90]

In [2]:
#넘파이 -> 리스트 간의 연산이 가능함 (배열 활용 np.array)
import numpy as np

mid_scores=np.array([10,20,30])
final_scores=np.array([70,80,90])

total=mid_scores+final_scores
print(total)

[ 80 100 120]


In [35]:
#실습
a=[10,20,30,40,50]
print(a[0])
print(a[0:1])
print(a[0:2])
print(a[0:3])
print(a[0:6])
print(a[-1])

c=[10,20,30]
c.append(40)
print(c)

c.insert(1,70)
print(c)

d=[100,200,300]
c.extend(d)
print(c)

10
[10]
[10, 20]
[10, 20, 30]
[10, 20, 30, 40, 50]
50
[10, 20, 30, 40]
[10, 70, 20, 30, 40]
[10, 70, 20, 30, 40, 100, 200, 300]


In [10]:
#인덱싱과 슬라이싱
import numpy as np
grades=np.array([88,72,93,94])

#인덱싱 - 특정한 요소 추출
#인덱스는 0부터 시작
print(grades[2])
print(grades[-1]) #마지막 요소는 인덱스 -1

#슬라이싱
print(grades[1:3])
print(grades[:2]) #시작 인덱스나 종료 인덱스는 생략 가능

#논리적인 인덱싱(logical indexing) - 어떤 조건을 주어서 배열에서 원하는 값을 추려내는 것
ages=np.array([18,19,25,30,28])

y=ages>20 #ages에서 20살 이상인 사람만 고르려고 한다면, 조건식 코딩
print(y) #결과는 부울형의 넘파이 배열

93
94
[72 93]
[88 72]
[False False  True  True  True]


In [12]:
#mean()
#numpy에서 제공하는 배열을 이용하면 배열에 저장된 원소들의 평균값을 계산
#array라는 메소드를 사용하여 1차원 배열 생성
#여기서 x라는 객체를 만들어 제공하는 mean()이라는 메소드를 이용하여 해당값을 구할 수 있다.

#numpy 모듈 가져오기
import numpy as np

#파이썬의 데이터형(예:리스트)을 numpy 형식으로 변환
x=np.array([1,3,5])

#numpy에서 제공하는 기능수행(예:평균)
print(x.mean())

3.0


In [20]:
#shape()
#해당 클래스에서 제공해주는 속성(attribute)
#배열의 형태를 튜플로 반

print(x)
print(x.shape) #(3,) #1차원 배열로 3개의 원소가 있다는 결과 출력

#2차원 배열 생성
a=np.array([[1,2,3],[2,3,4]])
print(a)
print(a.shape) #(2,3) #numpy 형식의 배열 a는 3개의 원소로 구성된 2개의 원소가 있다, 2X3의 2차원 배열


[1 3 5]
(3,)
[[1 2 3]
 [2 3 4]]
(2, 3)


In [22]:
#reshape()
#배열의 원소 입력할 때는 항상 리스트형식으로 입력
x=np.array([1,3,5])
print(x)

#reshape() 메소드를 추가하면 numpy의 2차원 배열을 원하는 모양으로 생성할 수 있음
x=np.array([1,3,5,7,9,11])
print(x)
x=np.array([1,3,5,7,9,11]).reshape(3,2)
print(x)

[1 3 5]
[ 1  3  5  7  9 11]
[[ 1  3]
 [ 5  7]
 [ 9 11]]


In [24]:
#zeros()
#괄호 안에 입력된 숫자만큼의 원소를 생성하고 0으로 초기화
#한 쌍의 괄호 [] 안에 숫자가 1개이면 벡터(1차원)를,
#두 쌍의 괄호 안에 숫자가 2개이면 행렬(2차원)을 생성

import numpy as np
x=np.zeros([2,3])
print(x)

[[0. 0. 0.]
 [0. 0. 0.]]


In [26]:
#ones()
#2차원 배열에 1의 값들을 채움

y=np.ones([3,4])
print(y)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [31]:
x=np.array([[1,3,5],[2,4,6]])
print(x)

print(x[1]) #2차원 배열의 첫번째 원소인 1차원 배열 출력
print(x[1].mean()) #첫번째 1차원 배열에 저장된 원소들의 평균값을 실수 형태로 출력
print(x.mean()) #x 배열 전체의 원소의 평균값을 구해 출력
print(x.shape) #x 배열의 (모양)형식을 출력

[[1 3 5]
 [2 4 6]]
[2 4 6]
4.0
3.5
(2, 3)


In [36]:
list1=[[1,11],[2,12],[3,13]]
print(list1[1][1])
print(list1[0][0])

12
1
